<?php

use Illuminate\Database\Seeder;
use App\Platform;

class PlatformsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        Platform::truncate();
        
        \DB::table('platforms')->insert(array (
            0 => 
            array (
                'id' => 1,
                'video_id' => 1,
                'platform_name' => 'CatchPlay+',
                'vod_id' => NULL,
                'vod_title' => '李察朱威爾事件',
                'vod_description' => '【美國狙擊手】金獎導演克林伊斯威特執導，改編自震撼人心的奧運爆炸案真實事件。戲精凱西貝茲雙料入圍奧斯卡與金球獎最佳女配角，【老娘叫譚雅】保羅沃爾特豪澤爾、【意外】奧斯卡最佳男配角山姆洛克威爾領銜主演。1996年亞特蘭大奧運會期間發生一起爆炸案，發現炸彈並報警的保安李察朱威爾竟意外在調查過程中從英雄變成囚徒；為了洗刷清白，他向獨立律師華森求助，一連串反體制的抗爭行動就此展開。',
                'vod_url' => 'https://www.catchplay.com/tw/video-407a6d16-be64-4c16-9cbb-0aba5bd7c137',
                'vod_provider' => 'warner bros digital distribution Home Enterta',
                'on_at' => '2020-04-19 18:03:48',
                'off_at' => '2021-04-20 18:03:48',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'video_id' => 2,
                'platform_name' => 'friDay',
                'vod_id' => NULL,
                'vod_title' => '極地守護犬',
                'vod_description' => '改編世界文學名著、20世紀百大小說《野性的呼喚》 靈犬巴克原本生活在充滿陽光的加州，沒想到卻意外被拐賣到寒冷偏遠、盛產黃金的北方阿拉斯加，巴克輾轉成為雪橇犬，流落在不同主人之間，在這淘金熱時期，等著它的不是安逸的生活，巴克必需呼喚起深藏內心的野性，來面對嚴峻的生存考驗，而最終它將回歸最原始的自己，並成為自己的主人… 極地的守護者。',
                'vod_url' => 'https://video.friday.tw/movie/detail/52283',
                'vod_provider' => NULL,
                'on_at' => NULL,
                'off_at' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'video_id' => 3,
                'platform_name' => 'myVideo',
                'vod_id' => NULL,
                'vod_title' => '天氣之子',
                'vod_description' => '高一那年夏天，帆高（醍醐虎汰朗 配音）離開位在離島的家鄉，獨自一人來到東京，拮据的生活迫使他不得不找份工作，最後來到一間專門出版奇怪超自然刊物的出版社擔任寫手。不久，東京開始下起連日大雨，彷彿暗示著帆高不順遂的未來，在這座繁忙城市裡到處取材的帆高邂逅了與弟弟相依為命，不可思議的美少女陽菜（森七菜 配音）。「等等就會放晴了喔。」陽菜這樣告訴著帆高，不久，頭頂的烏雲逐漸散去，耀眼的陽光灑落街道…',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/308207',
                'vod_provider' => NULL,
                'on_at' => NULL,
                'off_at' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'video_id' => 4,
                'platform_name' => 'Hami Video',
                'vod_id' => '122491',
                'vod_title' => '豹子頭林沖',
                'vod_description' => '宋徽宗年間，八十萬禁軍教頭林沖的妻子林娘子偶遇權臣高俅義子高衙內，高衙內垂涎她的美色，想要據為己有。林沖之友陸謙賣友求榮，助紂為虐，林沖中其計，持刀誤入白虎堂。後被發配滄州充軍，途中險遭毒手，幸得魯智深相救……',
                'vod_url' => 'https://hamivideo.hinet.net/product/122491.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2023-12-31 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:13',
                'updated_at' => '2020-07-12 22:20:13',
            ),
            4 => 
            array (
                'id' => 5,
                'video_id' => 5,
                'platform_name' => 'Hami Video',
                'vod_id' => '122505',
                'vod_title' => '特務機械女郎',
                'vod_description' => '矽谷私家偵探克萊德庫柏，被科技投資者聘請尋找失蹤的女人，一生的摯愛，她神秘消失了，繼可疑的線索抽絲剝解，庫珀遇到了一群漂亮的女人和可疑的人物角色，直到發現比他想像的事件更加的錯綜複雜撲朔迷離。',
                'vod_url' => 'https://hamivideo.hinet.net/product/122505.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2030-12-31 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:24',
                'updated_at' => '2020-07-12 22:20:24',
            ),
            5 => 
            array (
                'id' => 6,
                'video_id' => 6,
                'platform_name' => 'Hami Video',
                'vod_id' => '122504',
                'vod_title' => '巴爾幹防線',
                'vod_description' => '1999年，俄羅斯軍官貝克受令控制科索沃的普利斯提納機場，直到增援部隊抵達。此戰略目標同時也是阿爾巴尼亞的激進分子的本營，對北約而言亦極爲重要。貝克招募已被除役的往日同袍進行任務，然而組成的小隊成員只有寥寥數人，必須對抗上百名火力充足的激進分子，死守機場直到俄羅斯維和部隊抵達。',
                'vod_url' => 'https://hamivideo.hinet.net/product/122504.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2030-03-31 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:34',
                'updated_at' => '2020-07-12 22:20:34',
            ),
            6 => 
            array (
                'id' => 7,
                'video_id' => 7,
                'platform_name' => 'Hami Video',
                'vod_id' => '122852',
                'vod_title' => '華特',
                'vod_description' => '對戈蘭和他的菜鳥同夥來說，搶劫深夜中的超市，「幾乎」是最不可能出錯的新手任務了。趁傍晚即將打烊前，靠著躲進衛生紙捲後的藏身處，戈蘭一夥人「幾乎」完美地裡應外合，除了不小心輸入錯誤的密碼以外。而他們不知道的是，前來查看超市情況的警衛華特，會給他們上一堂永生難忘的超市購物禮儀課程。',
                'vod_url' => 'https://hamivideo.hinet.net/product/122852.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2030-03-23 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:45',
                'updated_at' => '2020-07-12 22:20:45',
            ),
            7 => 
            array (
                'id' => 8,
                'video_id' => 8,
                'platform_name' => 'Hami Video',
                'vod_id' => '122492',
                'vod_title' => '天火',
                'vod_description' => '『★中國首部火山電影 ★名導賽門魏斯特執導』天火島美得如同世外桃源，幾乎讓人忘記它位於“Ring of Fire”——全球知名的環太平洋火山帶。年輕的地質學家李曉夢為了研發首個火山監測系統“朱雀”，帶著團隊來到了這裡。李曉夢的父親、隱退多年的火山專家李文濤得知後趕到火山口，力圖勸說她離開。與此同時，探險專家正楠在美輪美奐的水下溶洞潛水，準備給女友佳慧一個浪漫的求婚……',
                'vod_url' => 'https://hamivideo.hinet.net/product/122492.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2023-12-31 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:55',
                'updated_at' => '2020-07-12 22:20:55',
            ),
            8 => 
            array (
                'id' => 9,
                'video_id' => 9,
                'platform_name' => 'Hami Video',
                'vod_id' => '119873',
                'vod_title' => '刺殺諾曼第',
                'vod_description' => '第二次世界大戰最白熱化的1944年，在盟軍登陸歐陸戰場之前，一群被稱為“骯髒十三人”的特種美國部隊跳傘進入諾曼第，深入敵營執行一項危險的致命刺殺任務。',
                'vod_url' => 'https://hamivideo.hinet.net/product/119873.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2023-12-31 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:05',
                'updated_at' => '2020-07-12 22:21:05',
            ),
            9 => 
            array (
                'id' => 10,
                'video_id' => 10,
                'platform_name' => 'Hami Video',
                'vod_id' => '121922',
                'vod_title' => '足球暴徒：復仇者',
                'vod_description' => '改編自真實犯罪事件。甫出獄的帕特回到西班牙復仇卻發現宿敵早已身亡，其毒品帝國被奸商泰瑞接管，想重操舊業的帕特只能接下這輩子最大一樁運毒案，接踵而來的麻煩事將這樁交易演變成一場公路危機之旅，兩個不靠譜的朋友為了回英國參加拳擊賽事，必須在有限的時間完成任務！！',
                'vod_url' => 'https://hamivideo.hinet.net/product/121922.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2025-03-31 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:15',
                'updated_at' => '2020-07-12 22:21:15',
            ),
            10 => 
            array (
                'id' => 11,
                'video_id' => 11,
                'platform_name' => 'Hami Video',
                'vod_id' => '122472',
                'vod_title' => '那個做對事的人自殺了',
                'vod_description' => '因為父親過世而回到家鄉的明石，發現父親告發了城鎮上受人敬重的中町汽車，卻被眾人唾棄。被孤兒院院長北村雇用後，明石才知道父親過去協助偷車集團，靠賺來的錢幫助孤兒院的孩子，明石自己也在幫助孤兒奈奈尋找生父時，發現了北村的秘密。這一連串的事件，讓明石越來越不明白，究竟什麼才叫正義，怎麼做才是對的。',
                'vod_url' => 'https://hamivideo.hinet.net/product/122472.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2027-02-11 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:26',
                'updated_at' => '2020-07-12 22:21:26',
            ),
            11 => 
            array (
                'id' => 12,
                'video_id' => 12,
                'platform_name' => 'Hami Video',
                'vod_id' => '121936',
                'vod_title' => '殺妻嫌疑',
                'vod_description' => '正浩一覺醒來得知分居妻子前一晚遭人殺害，他卻因為喝到斷片而記不得任何事情，然而各項證據都指出他就是兇手。為了證明自己的清白，他躲避警方的追查，試圖拼湊出事件的真相，但偶爾浮現的模糊記憶，讓他開始懷疑自己可能殺了妻子…',
                'vod_url' => 'https://hamivideo.hinet.net/product/121936.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2027-02-13 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:36',
                'updated_at' => '2020-07-12 22:21:36',
            ),
            12 => 
            array (
                'id' => 13,
                'video_id' => 13,
                'platform_name' => 'Hami Video',
                'vod_id' => '114094',
                'vod_title' => '絕命大平台',
                'vod_description' => '當葛蘭漸漸從昏迷中醒來時，發現自己身處在一座宛如監獄般建築的第48層，這座建築從地表往地底延伸，中間由巨大的方形洞貫穿，一個大平台會將上層住戶吃剩的食物一層層依序送下來。與他同一層的「獄友」崔馬加西知道關於這個神秘處所的規則：每層有兩個人，總人數不詳。如果有辦法往上就能生存，但如果想太多就會再次沉淪。如果在幾乎沒有食物送達的底層，除了自身的勇氣，誰都不能相信……',
                'vod_url' => 'https://hamivideo.hinet.net/product/114094.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-04-17 00:00:00',
                'off_at' => '2029-12-01 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:46',
                'updated_at' => '2020-07-12 22:21:46',
            ),
            13 => 
            array (
                'id' => 14,
                'video_id' => 14,
                'platform_name' => 'Hami Video',
                'vod_id' => '122493',
                'vod_title' => '拾光人生',
                'vod_description' => '正值中年的麥特（傑森蘇戴西斯 飾）投身音樂產業，面對日新月異的科技變遷，他卻覺得自己與整個大環境格格不入。麥特的父親班（艾德哈里斯 飾）則是一名善用底片的知名攝影師，如今也感受到數位革新似乎終結了自己的光榮時代。在班確診罹患重病之後，這對長年不合的父子終於再度聚首，和父親的助理柔伊（伊莉莎白歐森 飾）一同前往堪薩斯朝聖，達成班最後的心願──趕在世上僅存的柯達沖印坊熄燈之前，沖印出自己手上的幾卷剩餘底片。',
                'vod_url' => 'https://hamivideo.hinet.net/product/122493.do?cs=2',
                'vod_provider' => NULL,
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2023-12-31 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:59',
                'updated_at' => '2020-07-12 22:21:59',
            ),
            14 => 
            array (
                'id' => 15,
                'video_id' => 15,
                'platform_name' => 'friDay',
                'vod_id' => '53022',
                'vod_title' => '濟公',
                'vod_description' => '降龍羅漢是天上一名小小神仙， 一日降龍對玉帝出言不遜，險與伏虎羅漢一同被貶凡間為豬狗，最後眾仙達成協議，選定三個命中註定淪為「九世乞丐」、「九世妓女」、「九世惡人」之凡人，限令降龍在規定時間內加以感化改造，令他們能夠找回自尊並自願為他人犧牲，附帶條件是降龍不得帶法力下凡，倘能成功，則算降龍得勝，不予怪罪，否則便須再墮「涅槃」，受輪迴之苦。',
                'vod_url' => 'https://video.friday.tw/movie/detail/53022',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2022-02-03 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:22:10',
                'updated_at' => '2020-07-12 22:22:10',
            ),
            15 => 
            array (
                'id' => 16,
                'video_id' => 16,
                'platform_name' => 'friDay',
                'vod_id' => '53009',
                'vod_title' => '血衛（4K）',
                'vod_description' => '士兵雷葛瑞森在一次行動中陣亡，死後被帶至RST公司進行試驗，並成功以超人類「血衛」重生。他的血液中存在著一批奈米技術大軍，擁有一股不可阻擋的強大威力—不但能帶來比平常更猛的力量，還能夠及時痊癒。但除了他的身體，RST也同時抹去他的記憶。雷無法分辨什麼是真實，而他的使命，就是要找出真相。',
                'vod_url' => 'https://video.friday.tw/movie/detail/53009',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2025-07-12 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:22:20',
                'updated_at' => '2020-07-12 22:22:20',
            ),
            16 => 
            array (
                'id' => 17,
                'video_id' => 16,
                'platform_name' => 'friDay',
                'vod_id' => '53008',
                'vod_title' => '血衛',
                'vod_description' => '士兵雷葛瑞森在一次行動中陣亡，死後被帶至RST公司進行試驗，並成功以超人類「血衛」重生。他的血液中存在著一批奈米技術大軍，擁有一股不可阻擋的強大威力—不但能帶來比平常更猛的力量，還能夠及時痊癒。但除了他的身體，RST也同時抹去他的記憶。雷無法分辨什麼是真實，而他的使命，就是要找出真相。',
                'vod_url' => 'https://video.friday.tw/movie/detail/53008',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2025-07-12 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:22:30',
                'updated_at' => '2020-07-12 22:22:30',
            ),
            17 => 
            array (
                'id' => 18,
                'video_id' => 17,
                'platform_name' => 'friDay',
                'vod_id' => '52295',
                'vod_title' => '超級配音生死鬥',
                'vod_description' => '「就算地球今天要被毀滅，也要給我完成配音工作才能離開！」，「超狂！超瘋！超現實喜劇 誕生！！！」，曾經有個時期，配音演員的地位非常重要，無論是動畫、廣播劇、紀錄片，或各種需要旁白的電影，但曾幾何時，他們的地位漸漸不保，開始被沒有專業配音技術的明星、甚至是網紅、YouTuber給取代，越來越少的機會留給他們，這些正統的配音演員為了爭一口飯吃，也只能競爭得火熱。',
                'vod_url' => 'https://video.friday.tw/movie/detail/52295',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2026-01-03 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:22:40',
                'updated_at' => '2020-07-12 22:22:40',
            ),
            18 => 
            array (
                'id' => 19,
                'video_id' => 18,
                'platform_name' => 'friDay',
                'vod_id' => '52294',
                'vod_title' => '死了一個女高中生之後',
                'vod_description' => '「我最好的朋友自殺死了，大家都圍繞著我尋找真相…」，女高中生慶敏失蹤了，似乎是從橋上跳下去自殺，但沒找到屍體，也沒有留下遺書，最後一個陪在她身邊的迎熙，成了眾人的目標，大家都希望從她身上獲得一點蛛絲馬跡，然而一連串來自慶敏母親、班上同學的指控、懷疑、霸凌、獵巫，卻讓一切變得失控不已，而真相也變得不再重要……為了證明自己的清白，迎熙做了一個大膽的決定。',
                'vod_url' => 'https://video.friday.tw/movie/detail/52294',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2026-01-03 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:22:50',
                'updated_at' => '2020-07-12 22:22:50',
            ),
            19 => 
            array (
                'id' => 20,
                'video_id' => 19,
                'platform_name' => 'friDay',
                'vod_id' => '52293',
                'vod_title' => '靈異實錄（美國）',
                'vod_description' => '一位女警在調查同事的謀殺案的過程中意外發現有不明的超自然力量正糾纏著她所屬單位的同事們，起因竟是兩名白人警官刻意隱藏被穿戴式攝影機記錄到的黑人謀殺事件影片所起。',
                'vod_url' => 'https://video.friday.tw/movie/detail/52293',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2021-12-26 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:04',
                'updated_at' => '2020-07-12 22:23:04',
            ),
            20 => 
            array (
                'id' => 21,
                'video_id' => 20,
                'platform_name' => 'friDay',
                'vod_id' => '52292',
                'vod_title' => '藍色大街的少年',
                'vod_description' => '蒂米和馬可是從小一起長大的好朋友，在佩卡姆讀同一所高中，但卻住在鄰近的倫敦自治市鎮。 當馬可被蒂米的一個小學朋友毆打時，兩個男孩陷入幫派戰爭的敵對雙方，無休止的循環，在那裡沒有勝利者，只有受害者。',
                'vod_url' => 'https://video.friday.tw/movie/detail/52292',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2021-12-06 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:14',
                'updated_at' => '2020-07-12 22:23:14',
            ),
            21 => 
            array (
                'id' => 22,
                'video_id' => 21,
                'platform_name' => 'friDay',
                'vod_id' => '52290',
                'vod_title' => '不可能的任務：全面瓦解（4K）',
                'vod_description' => '伊森韓特在逮捕無政府恐怖組織「辛迪加」的領導人連恩後，接下新任務是阻止餘黨、以約翰拉克為首的12個「使徒」的瘋狂計畫，伊森韓特得早一步比「使徒」先拿到鈽元素，避免讓「使徒」在72小時內製造出核彈攻擊主要城市。然而，伊森韓特這項搶走鈽元素的任務執行失敗，他必須接受中情局的監督，讓中情局特務沃克（亨利卡維爾 飾演）進入IMF團隊，並且借助盟友伊爾莎的消息，合力再找回鈽元素。',
                'vod_url' => 'https://video.friday.tw/movie/detail/52290',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2021-01-03 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:24',
                'updated_at' => '2020-07-12 22:23:24',
            ),
            22 => 
            array (
                'id' => 23,
                'video_id' => 22,
                'platform_name' => 'friDay',
                'vod_id' => '52287',
                'vod_title' => '琴遇峇里島',
                'vod_description' => '年輕的峇里島男孩埃卡愛上了豪華別墅裡來自法國的年輕女子瑪歌，不會說法文的埃卡決定學習創作音樂，用樂音來跟瑪歌表達滿腔的愛意。文化的衝擊、身分的對立、語言的隔閡，這些巨大的鴻溝在這個“眾神之島－同時擁有稻田、山脈、火山和海灘的天堂”似乎不再重要…',
                'vod_url' => 'https://video.friday.tw/movie/detail/52287',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2027-01-03 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:36',
                'updated_at' => '2020-07-12 22:23:36',
            ),
            23 => 
            array (
                'id' => 24,
                'video_id' => 23,
                'platform_name' => 'friDay',
                'vod_id' => '52165',
                'vod_title' => '諜中諜',
                'vod_description' => '這是改編自波蘭英雄楊・諾瓦克經歷的真實故事。楊・諾瓦克曾在二次大戰的高峰期間，英勇擔任波蘭與倫敦的流亡政府之使者，因而被稱為「華沙使者」。不顧所有軸心國密使追捕他，他帶著至關波蘭及戰爭命運的密令偷渡至倫敦，並在路途中沿路被德軍跟蹤演出一場諜報大戰，此時卻結識了改變他一生的戰士們。',
                'vod_url' => 'https://video.friday.tw/movie/detail/52165',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2025-06-13 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:47',
                'updated_at' => '2020-07-12 22:23:47',
            ),
            24 => 
            array (
                'id' => 25,
                'video_id' => 24,
                'platform_name' => 'friDay',
                'vod_id' => '52164',
                'vod_title' => '狂暴猛獅',
                'vod_description' => '一家人在農場附近遭到殺害，阿姆斯特丹的警方找不到任何線索，獸醫麗茲卻發現了關鍵跡象，使她懷疑兇手是一隻大獅子。一開始，她的理論不被重視，但在更多受害者出現後，人們開始相信這隻猛獅已經入侵阿姆斯特丹了。政府請來英籍的大型動物獵人與麗茲合作。然而，在調查的同時，她還得確保自己身為記者的男友不會為了新聞失了分寸。而另一邊，大開殺戒的獅子已即將讓整個城市變成牠的狩獵場。',
                'vod_url' => 'https://video.friday.tw/movie/detail/52164',
                'vod_provider' => NULL,
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2025-06-08 23:59:59',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:02',
                'updated_at' => '2020-07-12 22:24:02',
            ),
            25 => 
            array (
                'id' => 26,
                'video_id' => 11,
                'platform_name' => 'myVideo',
                'vod_id' => '0/309498',
                'vod_title' => '那個做對事的人自殺了',
                'vod_description' => '因為父親過世而回到家鄉的明石，發現父親告發了城鎮上受人敬重的中町汽車，卻被眾人唾棄。被孤兒院院長北村雇用後，明石才知道父親過去協助偷車集團，靠賺來的錢幫助孤兒院的孩子，明石自己也在幫助孤兒奈奈尋找生父時，發現了北村的秘密。這一連串的事件，讓明石越來越不明白，究竟什麼才叫正義，怎麼做才是對的。',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/309498',
                'vod_provider' => '原創娛樂股份有限公司',
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2027-02-11 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:08',
                'updated_at' => '2020-07-12 22:24:08',
            ),
            26 => 
            array (
                'id' => 27,
                'video_id' => 25,
                'platform_name' => 'myVideo',
                'vod_id' => '0/306073',
                'vod_title' => '長沙里之戰：被遺忘的英雄',
                'vod_description' => '李明俊大尉為了讓「仁川登陸戰」能順利進行，便率領游擊隊和僅受過兩週軍事訓練的772名學生兵們，前往長沙里展開聲東擊西的「長沙登陸戰」。平均年齡17歲的學生兵們，該如何在惡劣的天氣中躲過槍林彈雨的攻擊，成功完成任務呢？',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/306073',
                'vod_provider' => '車庫娛樂股份有限公司',
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2023-12-31 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:17',
                'updated_at' => '2020-07-12 22:24:17',
            ),
            27 => 
            array (
                'id' => 28,
                'video_id' => 8,
                'platform_name' => 'myVideo',
                'vod_id' => '0/307630',
                'vod_title' => '天火',
                'vod_description' => '天火島美得如同世外桃源，幾乎讓人忘記它位於“Ring of Fire”——全球知名的環太平洋火山帶。年輕的地質學家李曉夢為了研發首個火山監測系統“朱雀”，帶著團隊來到了這裡。李曉夢的父親、隱退多年的火山專家李文濤得知後趕到火山口，力圖勸說她離開。與此同時，探險專家正楠在美輪美奐的水下溶洞潛水，準備給女友佳慧一個浪漫的求婚……',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/307630',
                'vod_provider' => '車庫娛樂股份有限公司',
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2023-12-31 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:23',
                'updated_at' => '2020-07-12 22:24:23',
            ),
            28 => 
            array (
                'id' => 29,
                'video_id' => 14,
                'platform_name' => 'myVideo',
                'vod_id' => '0/307646',
                'vod_title' => '拾光人生',
                'vod_description' => '正值中年的麥特（傑森蘇戴西斯 飾）投身音樂產業，面對日新月異的科技變遷，他卻覺得自己與整個大環境格格不入。麥特的父親班（艾德哈里斯 飾）則是一名善用底片的知名攝影師，如今也感受到數位革新似乎終結了自己的光榮時代。
在班確診罹患重病之後，這對長年不合的父子終於再度聚首，和父親的助理柔伊（伊莉莎白歐森 飾）一同前往堪薩斯朝聖，達成班最後的心願──趕在世上僅存的柯達沖印坊熄燈之前，沖印出自己手上的幾卷剩餘底片。',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/307646',
                'vod_provider' => '車庫娛樂股份有限公司',
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2023-12-31 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:32',
                'updated_at' => '2020-07-12 22:24:32',
            ),
            29 => 
            array (
                'id' => 30,
                'video_id' => 26,
                'platform_name' => 'myVideo',
                'vod_id' => '0/308212',
                'vod_title' => '蜈蚣降',
                'vod_description' => '哈尼夫帶著妻小和幾個好友，打算回到幼時成長的孤兒院，探望年事已高、身體孱弱的看護班迪先生。然而，當一行人抵達孤兒院後情況卻急轉直下，恐怖駭人的超自然事件接連襲來，本該溫馨的重逢場合一夜之間化為人間煉獄，揭露一段不為人知的黑暗過往……',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/308212',
                'vod_provider' => '車庫娛樂股份有限公司',
                'on_at' => '2020-06-26 00:00:00',
                'off_at' => '2023-12-31 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:40',
                'updated_at' => '2020-07-12 22:24:40',
            ),
            30 => 
            array (
                'id' => 31,
                'video_id' => 27,
                'platform_name' => 'myVideo',
                'vod_id' => '0/308969',
                'vod_title' => '大魔術師',
                'vod_description' => '東方魔術師張賢（梁朝偉 飾）憑著精湛的手法一夕爆紅。雷大帥（劉青雲 飾）為了贏得小妾柳蔭（周迅 飾）的芳心，相偕去看柳蔭最喜歡的魔術表演。柳蔭更是開始對雷大帥釋出好感，可雷大帥怎麼也沒料到這一切卻是場精心安排的瞞天大佈局！一場耗費十年精心安排的人生戲法，是否能如張賢所願，從殺人如麻的軍閥手中搶回真愛呢?',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/308969',
                'vod_provider' => '鴻聯國際開發股份有限公司',
                'on_at' => '2020-06-30 00:00:00',
                'off_at' => '2021-12-31 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:49',
                'updated_at' => '2020-07-12 22:24:49',
            ),
            31 => 
            array (
                'id' => 32,
                'video_id' => 28,
                'platform_name' => 'myVideo',
                'vod_id' => '0/310564',
                'vod_title' => '騎機男孩2',
                'vod_description' => '阿薩考上銀行行員後，與佳茹戀情漸入佳境。佳茹便帶著阿薩和一群親友回老家拜訪父親。但佳茹父親是個老古板，希望為佳茹找到門當戶對的男友，因此伯伯裝起闊氣，浮誇的機車夥伴們化身落漆機師，一群人與古板父親撞出許多激情火花！',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/310564',
                'vod_provider' => '采昌國際多媒體股份有限公司',
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2022-06-30 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:58',
                'updated_at' => '2020-07-12 22:24:58',
            ),
            32 => 
            array (
                'id' => 33,
                'video_id' => 29,
                'platform_name' => 'myVideo',
                'vod_id' => '0/309645',
                'vod_title' => '聲入奇境：經典配樂大師',
                'vod_description' => '本片精彩收錄：《阿拉伯的勞倫斯》配樂家、三座小金人得主Maurice Jarre；《小宇宙》《喜馬拉雅》《放牛班的春天》三座凱薩獎得主Bruno Coulais；楚浮《夏日之戀》、高達《輕蔑》等法國新浪潮作曲大師Georges Delerue；《英倫情人》小金人得主Gabriel Yared；《歡迎來到布達佩斯大飯店》、《水底情深》二屆小金人得主Alexandre Desplat；《大河戀》、《衝擊效應》配樂家Mark Isham；創作出《不可能的任務》招牌旋律的Lalo Schifrin；《大鼻子情聖》凱薩獎得主Jean-Claude Petit；以及《男歡女愛》配樂家Francis Lai，與《戀愛夢遊中》坎城電影音樂獎得主Jean-Michel Bernard跨世代精采對談。',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/309645',
                'vod_provider' => '佳映娛樂國際股份有限公司',
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2024-11-24 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:25:06',
                'updated_at' => '2020-07-12 22:25:06',
            ),
            33 => 
            array (
                'id' => 34,
                'video_id' => 30,
                'platform_name' => 'myVideo',
                'vod_id' => '0/311382',
                'vod_title' => '戀愛完成式2',
                'vod_description' => '四年前，小拓和歐愛在他鄉的日本之戀無疾而終，令小拓深受打擊。苦等四年的小拓終於決定不再盼望歐回心轉意，並前往遠離泰國本土的孤島－閣骨島黯然療傷，也遇見來自日本的帥氣開朗男孩健太。島上的寧靜與美麗，終於令小拓重拾歡樂與笑聲。某天晚上，小拓突然收到歐的訊息、得知歐對他始終無法忘懷，卻也無法隱忍對歐仍然強烈的思念，即使他深知這段愛情不可能開花結果。隔天早上，歐竟來到閣骨島、出現在小拓的面前，他是否該聽從內心、與歐再續前緣？或是認清事實、與歐就此訣別？',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/311382',
                'vod_provider' => '杰德創意影音管理股份有限公司',
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2021-07-01 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:25:15',
                'updated_at' => '2020-07-12 22:25:15',
            ),
            34 => 
            array (
                'id' => 35,
                'video_id' => 31,
                'platform_name' => 'myVideo',
                'vod_id' => '0/309475',
                'vod_title' => 'X+Y愛的方程式',
                'vod_description' => '一名罹患亞斯柏格症的青少年奈森，從小便無法與人溝通，加上父親在面前車禍逝世的陰影，他甚至排斥自己的母親茱莉。奈森天生就喪失了愛的能力，唯有在數學的世界能使他找到慰藉。因為對數學的熱忱與天分他進入了英國數學國家隊，跟著團隊遠赴重洋來到台灣參加國際數學奧林匹亞競賽選手集訓 ，直到在台灣遇上中國少女張梅讓他漸漸敞開了心房，真正開始理解愛，繼而逐步解開人生方程式。',
                'vod_url' => 'https://www.myvideo.net.tw/details/0/309475',
                'vod_provider' => '捷傑有限公司',
                'on_at' => '2020-07-01 00:00:00',
                'off_at' => '2023-01-11 00:00:00',
                'status' => 1,
                'created_at' => '2020-07-12 22:25:23',
                'updated_at' => '2020-07-12 22:25:23',
            ),
        ));
        
        
    }
}