<?php

use Illuminate\Database\Seeder;
use App\Video;

class VideosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        Video::truncate();
        
        \DB::table('videos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => '李察朱威爾事件',
                'title_en' => 'Richard Jewell',
                'description' => '本片改編自1997年刊登於《Vanity Fair》雜誌上的一篇文章《美國惡夢》，真實事件改編。描述當不實的報導被當作事實時，真相會如何被遮掩的故事，一名英雄卻成了頭號嫌犯。',
                'description_en' => 'American security guard Richard Jewell saves many lives from an exploding bomb at the 1996 Olympics, but is vilified by journalists and the press who falsely reported that he was a terrorist.',
                'year' => 2019,
                'poster_url' => 'https://r3sub.com/posters/3513548.jpg',
                'imdb_id' => 'tt3513548',
                'atmovies_id' => 'fben53513548',
                'douban_id' => '25842038',
                'status' => 1,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-20 18:03:48',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => '極地守護犬',
                'title_en' => 'The Call of the Wild',
                'description' => '根據美國經典文學傑克倫敦的同名小說改編的真人電影。哈里遜福特與真狗CG動畫搭配演出，一人一犬踏上荒蕪的冒險之旅，前往世界的盡頭，大聲回應野性的呼喚。',
                'description_en' => 'A sled dog struggles for survival in the wilds of the Yukon.',
                'year' => 2020,
                'poster_url' => 'https://r3sub.com/posters/7504726.jpg',
                'imdb_id' => 'tt7504726',
                'atmovies_id' => 'fcen47504726',
                'douban_id' => '27199324',
                'status' => 1,
                'created_at' => '2020-05-20 20:00:00',
                'updated_at' => '2020-05-20 20:00:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => '天氣之子',
                'title_en' => 'Weathering With You',
                'description' => '新海誠作品，本片是以「世界氣候異常」為主題，被命運捉弄的少年和少女的愛情故事，描述能以祈禱操控天氣的不可思議美少女天野陽菜與少年森島高帆。',
                'description_en' => 'A high-school boy who has run away to Tokyo befriends a girl who appears to be able to manipulate the weather.',
                'year' => 2019,
                'poster_url' => 'https://r3sub.com/posters/9426210.jpg',
                'imdb_id' => 'tt9426210',
                'atmovies_id' => 'fwjp49426210',
                'douban_id' => '30402296',
                'status' => 1,
                'created_at' => '2020-06-15 22:00:00',
                'updated_at' => '2020-06-15 22:00:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => '豹子頭林沖',
                'title_en' => 'The Man Named Leopard',
                'description' => '宋徽宗年間，八十萬禁軍教頭林沖的妻子林娘子偶遇權臣高俅義子高衙內，高衙內垂涎她的美色，想要據為己有。林沖之友陸謙賣友求榮，助紂為虐，林沖中其計，持刀誤入白虎堂。後被發配滄州充軍，途中險遭毒手，幸得魯智深相救……',
                'description_en' => NULL,
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/raZ9B7tD6NyHwsWNIh3U13slwCw.jpg',
                'imdb_id' => 'tt11306712',
                'atmovies_id' => NULL,
                'douban_id' => '30379825',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:13',
                'updated_at' => '2020-07-12 22:20:13',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => '特務機械女郎',
                'title_en' => 'Girls After Dark',
                'description' => NULL,
                'description_en' => 'A private investigator is hired to track down a missing girl on the run from a mysterious Silicon Valley corporation.',
                'year' => 2018,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/6gTe5LyA5wjdQAWy7aEnrNpMFMq.jpg',
                'imdb_id' => 'tt6876788',
                'atmovies_id' => NULL,
                'douban_id' => '30391281',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:24',
                'updated_at' => '2020-07-12 22:20:24',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => '巴爾幹防線',
                'title_en' => 'The Balkan Line',
                'description' => '1999年, 南斯拉夫。 俄羅斯特遣部隊被命令控制科索沃的斯拉蒂納機場，直到增援部隊抵達。但這一戰略目標對於阿爾巴尼亞戰地指揮官和北約將軍來說極為重要。該組織被迫與恐怖分子進行不平等的戰鬥。俄羅斯維和部隊和北約部隊正趕往機場。世界再次接近一場大戰。但是特別組織的指揮官安德烈 ‧沙塔洛夫並不接受政治：在機場，他心愛的女孩亞斯納是人質之一...…',
                'description_en' => 'After the NATO bombing of Yugoslavia in 1999, the Yugoslav army pulls out of Kosovo region, leaving Serbian people at the mercy of the Albanian UCK terrorists. A small band of soldiers must take over the Slatina airport, and hold it until the Russian peacekeepers arrive.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/4RiErfUUtIsdVZyTkgsaK4NyabQ.jpg',
                'imdb_id' => 'tt5951188',
                'atmovies_id' => NULL,
                'douban_id' => '30391372',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:34',
                'updated_at' => '2020-07-12 22:20:34',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => '華特',
                'title_en' => 'Walter',
                'description' => '對戈蘭和他的菜鳥同夥來說，搶劫深夜中的超市，「幾乎」是最不可能出錯的新手任務了。趁傍晚即將打烊前，靠著躲進衛生紙捲後的藏身處，戈蘭一夥人「幾乎」完美地裡應外合，除了不小心輸入錯誤的密碼以外。而他們不知道的是，前來查看超市情況的警衛華特，會給他們上一堂永生難忘的超市購物禮儀課程。',
                'description_en' => 'or Goran and his team of amateur shooters, the plan was almost perfect: to enter a hypermarket at night to rob a jeweler. But these "broken arms" had not anticipated the arrival of a vigil like no other: Walter, a former African warlord who will send them to hell .',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/cUrsX3QO8kxiOo8ZU2vmMwjIC1H.jpg',
                'imdb_id' => 'tt9680064',
                'atmovies_id' => NULL,
                'douban_id' => '30462403',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:45',
                'updated_at' => '2020-07-12 22:20:45',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => '天火',
                'title_en' => 'Skyfire',
                'description' => '年輕的地質學家李曉夢為了研發首個火山監測系統“朱雀”，帶著團隊來到了這裡。　火山噴發了，這些人的命運糾結在一起。為了看見明天的太陽，他們必須與過去和解，合力為自己也為眾生在絕境中尋找一條生路。這是一個關於愛與勇氣、選擇與放棄的故事。',
                'description_en' => 'Tianhuo Island is as beautiful as a paradise. It almost makes people forget that it is located in the "Ring of Fire" the world-famous Pacific Rim volcanic belt. Young geologist Li Xiaomeng brought the team here to develop the first volcanic monitoring system, the Suzaku. Li Xiaomeng\'s father, Li Wentao, a volcanic expert who has retired for many years, rushed to the crater after learning about it, trying to persuade her to leave. At the same time, expedition expert Zheng Nan dived in the beautiful underwater cave, preparing to give his girlfriend Jiahui a romantic proposal. The volcano erupted, and the fate of these people was entangled. In order to see the sun of tomorrow, they must reconcile with the past, and work together to find a way for themselves and for all sentient beings in a desperate situation. This is a story about Chinese heroes who love and courage, choose and abandon, save themselves and save others.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/2BMLjpOUNPZmVlmk5q34JkTe6Eh.jpg',
                'imdb_id' => 'tt9203190',
                'atmovies_id' => 'fscn29203190',
                'douban_id' => '30357885',
                'status' => 1,
                'created_at' => '2020-07-12 22:20:55',
                'updated_at' => '2020-07-12 22:51:08',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => '刺殺諾曼第',
                'title_en' => 'D-Day Assassins',
                'description' => NULL,
                'description_en' => 'In 1944, group of rebellious American soldiers known as "The Filthy Thirteen" parachute into Normandy to carry out a deadly mission.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/29xobLkZsJW0Ifdc1lsNohZoaJH.jpg',
                'imdb_id' => 'tt5220602',
                'atmovies_id' => NULL,
                'douban_id' => '30437899',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:05',
                'updated_at' => '2020-07-12 22:21:05',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => '足球暴徒：復仇者',
                'title_en' => 'Rise of the Footsoldier: The Heist',
                'description' => '改編自真實犯罪事件。甫出獄的帕特回到西班牙復仇卻發現宿敵早已身亡，其毒品帝國被奸商泰瑞接管，想重操舊業的帕特只能接下這輩子最大一樁運毒案，接踵而來的麻煩事將這樁交易演變成一場公路危機之旅，兩個不靠譜的朋友為了回英國參加拳擊賽事，必須在有限的時間完成任務！！',
                'description_en' => 'Fresh out of prison, Pat Tate steps right back into his Essex nightclub. But still disgruntled, he soon sets out to Marbelle to revenge those that put him away for five years. While in Spain, Pat cannot turn away from the opportunity to score the biggest drug deal of his life. All he needs is for his Essex pals Tony and Craig to deliver the cash to Marbella to close the deal. But Craig, useless as ever, turns a simple plane trip to a massive road trip packed with trickery and danger. And Tony is more worried about making it back to England as he has promised to support his best friend Nigel Benn at the boxing match of his life. While waiting in Marbella, Pat proceeds with the violent revenge he has craved for years. Revenges are made and Tony and Carlton walk Nigel Benn out to what turns out to be one of the most tragic fights in history. But the drugs they bring back seems to be a bad batch and cause them more trouble than they have ever anticipated before.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/7ar8QNd4JeKeORDXNiM8fobdmvE.jpg',
                'imdb_id' => 'tt8769300',
                'atmovies_id' => 'fren78769300',
                'douban_id' => '30294889',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:15',
                'updated_at' => '2020-07-12 22:50:36',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => '那個做對事的人自殺了',
                'title_en' => 'Day and Night',
                'description' => NULL,
                'description_en' => 'A man suicides causing ruin for his family, reasons are unknown, but his son will decide to take revenge after a succesion of events.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/eoEcGPV7zDG4onmW5WNFNzgrAY9.jpg',
                'imdb_id' => 'tt9020768',
                'atmovies_id' => NULL,
                'douban_id' => '27135576',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:26',
                'updated_at' => '2020-07-12 22:21:26',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => '殺妻嫌疑',
                'title_en' => 'Killed My Wife',
                'description' => '老婆死了，但我什麼都不記得了？！
 正浩一覺醒來得知分居妻子前一晚遭人殺害，他卻因為喝到斷片而記不得任何事情，然而各項證據都指出他就是兇手。為了證明自己的清白，他躲避警方的追查，試圖拼湊出事件的真相，但偶爾浮現的模糊記憶，讓他開始懷疑自己可能殺了妻子…',
                'description_en' => 'Jung-ho, whose estranged wife is found dead, is suspected of murder but remembers nothing about the evening. Will his memory return? Is he innocent?',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/jTpuSDJVSDw3HL8VAWSrpGXpVww.jpg',
                'imdb_id' => 'tt11454162',
                'atmovies_id' => NULL,
                'douban_id' => '34842248',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:36',
                'updated_at' => '2020-07-12 22:21:36',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => '絕命大平台',
                'title_en' => 'The Platform',
                'description' => '每個人都要吃，每個人都想活，每個人都想逃脫！  當葛蘭漸漸從昏迷中醒來時，發現自己身處在一座宛如監獄般建築的第48層，這座建築從地表往地底延伸，中間由巨大的方形洞貫穿，一個大平台會將上層住戶吃剩的食物一層層依序送下來。與他同一層的「獄友」崔馬加西知道關於這個神秘處所的規則：每層有兩個人，總人數不詳。如果有辦法往上就能生存，但如果想太多就會再次沉淪。如果在幾乎沒有食物送達的底層，除了自身的勇氣，誰都不能相信……',
                'description_en' => 'A mysterious place, an indescribable prison, a deep hole. An unknown number of levels. Two inmates living on each level. A descending platform containing food for all of them. An inhuman fight for survival, but also an opportunity for solidarity…',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/l9Cuwfv3kEhdUhTSMsqpkUmTBYc.jpg',
                'imdb_id' => 'tt8228288',
                'atmovies_id' => 'fpes58228288',
                'douban_id' => '34805219',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:46',
                'updated_at' => '2020-07-12 22:49:29',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => '拾光人生',
                'title_en' => 'Kodachrome',
                'description' => '正值中年的麥特（傑森蘇戴西斯 飾）投身音樂產業，然而面對日新月異的科技變遷，他卻覺得自己與整個大環境越發格格不入。麥特的父親班（艾德哈里斯 飾）則是一名善用底片的知名攝影師，如今也感受到數位革新似乎終結了自己的光榮時代。  在班確診罹患重病之後，這對長年不合的父子終於再度聚首，和父親的助理柔伊（伊莉莎白歐森 飾）一同前往堪薩斯朝聖，達成班最後的心願──趕在世上僅存的柯達沖印坊熄燈之前，沖印出自己手上的幾卷剩餘底片。一心追尋純粹和真實、卻在現實逐漸不得志的兩人，也在這段旅途重新辯證彼此的關係……',
                'description_en' => 'Matt Ryder is convinced to drive his estranged and dying father Benjamin Ryder cross country to deliver four old rolls of Kodachrome film to the last lab in the world that can develop them before it shuts down for good. Along with Ben\'s nurse Zooey, the three navigate a world changing from analogue to digital while trying to put the past behind them.',
                'year' => 2017,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/td9tYff9zBcnlASSoulxNEuayaM.jpg',
                'imdb_id' => 'tt1880399',
                'atmovies_id' => 'fken41880399',
                'douban_id' => '21349343',
                'status' => 1,
                'created_at' => '2020-07-12 22:21:59',
                'updated_at' => '2020-07-12 22:42:53',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => '濟公',
                'title_en' => 'The Mad Monk',
                'description' => '位列羅漢的一名小仙“伏虎羅漢”，本性反叛，抱打不平，某次與掌管凡間“際遇”之神發生爭執，認為他弄權力，妄顧人間之疾苦，“際遇”（命運）之神則指人性頑劣，非經嚴峻考驗及懲罰，根本不能令人向善果。  眾仙達成協議與伏虎（周星馳飾）作一個輸賭，若伏虎能在一個時限內，讓指定的三名凡人能夠甘願為他人作自我犧牲，便是得勝，否則伏虎便要再墮“涅槃”，再受“輪迴”之苦。協議既定，伏虎便降世投胎，成年後皈依佛門，行徑怪異不落俗情，被冠以“濟公和尚”之名。  三個目標人物：一個是由於祖先犯錯而被上天了“九世為丐”的乞兒（黃秋生飾）。一個是受男人玩弄，女人唾罵的妓女（張曼玉飾）。另一個殺人如麻的大盜（黃志強飾）。  在濟公鬼馬機智的安排下，最後點化了九世惡人與九世乞兒，而妓女則愛上了濟公，不能接受凡塵之愛的濟公假死，以讓她死心，但痴情的妓女卻為他投河自盡，妓女對“愛”的執著及犧牲，感動了濟公故放棄了小乘修為，決心留在人間渡化百姓....。',
            'description_en' => 'Stephen Chow plays an angel-type being in this movie, in where he bets the other people in Heaven that he can change the ways of 3 misguided souls and make them better people. Ressurected as a monk, he must stop a prostitute, a beggar, and an all around bad guy from being what they are (and have been for generations). To add to all of this, he must do this in 3 Heaven days!!!',
                'year' => 1993,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/fzpqqUPNvQQsHYZkTAsgTSvcPO3.jpg',
                'imdb_id' => 'tt0106538',
                'atmovies_id' => 'fRatm0862006',
                'douban_id' => '1400665',
                'status' => 1,
                'created_at' => '2020-07-12 22:22:10',
                'updated_at' => '2020-07-12 22:42:43',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => '血衛',
                'title_en' => 'Bloodshot',
            'description' => '士兵雷葛瑞森 (馮迪索 飾) 在一次行動中陣亡，死後被帶至RST公司進行試驗，並成功以超人類「血衛」重生。他的血液中存在著一批奈米技術大軍，擁有一股不可阻擋的強大威力—不但能帶來比平常更猛的力量，還能夠及時痊癒。  但除了他的身體，RST也同時抹去他舊有的記憶，並控制他的思想。雷無法分辨什麼是真實還是捏造的假象，而他的使命，就是要找出真相。',
                'description_en' => 'After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—\'Bloodshot\'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there\'s more to the conspiracy than he thought.',
                'year' => 2020,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/pEAfW2OfXwSUUZ5B1Pu7BqG1DZ3.jpg',
                'imdb_id' => 'tt1634106',
                'atmovies_id' => NULL,
                'douban_id' => '4830483',
                'status' => 1,
                'created_at' => '2020-07-12 22:22:20',
                'updated_at' => '2020-07-12 22:22:20',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => '超級配音生死鬥',
                'title_en' => 'Beautiful Voice',
                'description' => '「就算地球今天要被毀滅，也要給我完成配音工作才能離開！」「超狂！超瘋！超現實喜劇 誕生！！！」曾經有個時期，配音演員的地位非常重要，無論是動畫、廣播劇、紀錄片，或各種需要旁白的電影，但曾幾何時，他們的地位漸漸不保，開始被沒有專業配音技術的明星、甚至是網紅、YouTuber給取代，越來越少的機會留給他們，這些正統的配音演員為了爭一口飯吃，也只能競爭得火熱。一群來自不同背景的配音演員為了一個遊戲案子，齊聚在電話亭大小的玻璃錄音室裡，而他們的期限就是今天。遭受錄音室外的眾多壓力，各形各色的崩潰挫折齊生，配音內容也開始荒腔走板，到後來一場不可思議的「英雄旅程」超展開……這是一封獻給所有有尊嚴的配音員的情書，不，是挑戰書！',
                'description_en' => 'Poor voice actors have a project that they have to finish dubbing in just one day. However, they are cramped in a tiny glass booth and tired of being treated like dirt by those above them. Unexpectedly, their story turns into one of heroes who adventure to space.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/3qGZCaUIg4aqbkl2d5dAem3LLwl.jpg',
                'imdb_id' => 'tt10338208',
                'atmovies_id' => NULL,
                'douban_id' => '34972334',
                'status' => 1,
                'created_at' => '2020-07-12 22:22:40',
                'updated_at' => '2020-07-12 22:22:40',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => '死了一個女高中生之後',
                'title_en' => 'After My Death',
                'description' => NULL,
                'description_en' => 'When a school girl disappears, suicide is suspected, and one of her classmates is suspected of having goaded her into it.',
                'year' => 2017,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/iRq94MzpctCyj0X44bT8Hkwxb9p.jpg',
                'imdb_id' => 'tt7390044',
                'atmovies_id' => NULL,
                'douban_id' => '27126713',
                'status' => 1,
                'created_at' => '2020-07-12 22:22:50',
                'updated_at' => '2020-07-12 22:22:50',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => '靈異實錄（美國）',
                'title_en' => 'Body Cam',
                'description' => '資深女警蕾妮的同事遭到離奇謀殺，調查過程中，她發現死者身上的穿戴式攝影機拍到了詭異人影。隨著蕾妮腦中不斷浮現兇案現場的幻覺，她開始懷疑是否有超自然力量正糾纏她所屬的單位。在竭力拯救同事時，蕾妮卻意外發現了警局的驚人黑幕，而這一切似乎就是連串靈異事件的源頭...',
                'description_en' => 'Cops involved with covering up a murder by getting rid of their body cam video footage find themselves haunted by an evil spirit.',
                'year' => 2020,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/q49txqdoFWCGUeEDZMx92LQq8sD.jpg',
                'imdb_id' => 'tt8179024',
                'atmovies_id' => NULL,
                'douban_id' => '30254068',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:04',
                'updated_at' => '2020-07-12 22:23:04',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => '藍色大街的少年',
                'title_en' => 'Blue Story',
                'description' => '蒂米和馬可是從小一起長大的好朋友，在佩卡姆讀同一所高中，但卻住在鄰近的倫敦自治市鎮。當馬可被蒂米的一個小學朋友毆打時，兩個男孩陷入幫派戰爭的敵對雙方，無休止的循環，在那裡沒有勝利者，只有受害者。',
                'description_en' => 'Blue Story is a tragic tale of a friendship between Timmy and Marco, two young boys from opposing postcodes. Timmy, a shy, smart, naive and timid young boy from Deptford, goes to school in Peckham where he strikes up a friendship with Marco, a charismatic, streetwise kid from the local area. Although from warring postcodes, the two quickly form a firm friendship until it is tested and they wind up on rival sides of a street war. Blue Story depicts elements of Rapman\'s own personal experiences and aspects of his childhood.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/3o9aKW3heDQPjNrpVErQOgcd4hd.jpg',
                'imdb_id' => 'tt9285882',
                'atmovies_id' => NULL,
                'douban_id' => '34874774',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:14',
                'updated_at' => '2020-07-12 22:23:14',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => '不可能的任務：全面瓦解',
                'title_en' => 'Mission: Impossible - Fallout',
            'description' => '劇情描述伊森韓特(湯姆克魯斯 飾演)在逮捕無政府恐怖組織「辛迪加」的領導人連恩後，接下新任務是阻止餘黨、以約翰拉克為首的12個「使徒」的瘋狂計畫，伊森韓特得早一步比「使徒」先拿到鈽元素，避免讓「使徒」在72小時內製造出核彈攻擊主要城市。然而，伊森韓特這項搶走鈽元素的任務執行失敗，他必須接受中情局的監督，讓中情局特務沃克(亨利卡維爾 飾演)進入IMF團隊，並且借助盟友伊爾莎(蕾貝卡弗格森 飾演)的消息，合力再找回鈽元素。',
                'description_en' => 'When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfill his original briefing, the CIA begin to question his loyalty and his motives. The IMF team find themselves in a race against time, hunted by assassins while trying to prevent a global catastrophe.',
                'year' => 2018,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/poyRwLq44HxlfoOspdcMicQlkuo.jpg',
                'imdb_id' => 'tt4912910',
                'atmovies_id' => 'fmen74912910',
                'douban_id' => '26336252',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:24',
                'updated_at' => '2020-07-12 22:44:53',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'title' => '琴遇峇里島',
                'title_en' => 'A Barge on the Ocean',
                'description' => NULL,
                'description_en' => 'Eka is a young Balinese living in a small village north of Bali. For love of Margaux, a French student expatriate on the island, Eka decided to learn how to compose music.',
                'year' => 2020,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/v2cuWASCiqq8cRQS2axZCPdrJRB.jpg',
                'imdb_id' => 'tt9659926',
                'atmovies_id' => 'faen59659926',
                'douban_id' => '34608179',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:36',
                'updated_at' => '2020-07-12 22:45:23',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'title' => '諜中諜',
                'title_en' => 'The Messenger',
                'description' => NULL,
                'description_en' => 'Film about the lead up to the Polish uprising against German occupation at the end of the Second World War.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/77vozcTUFugE2BF4EEzbVzoE7zV.jpg',
                'imdb_id' => 'tt8706988',
                'atmovies_id' => NULL,
                'douban_id' => '33390318',
                'status' => 1,
                'created_at' => '2020-07-12 22:23:47',
                'updated_at' => '2020-07-12 22:23:47',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'title' => '狂暴猛獅',
                'title_en' => 'Prooi',
                'description' => '一家人在農場附近遭到殺害，阿姆斯特丹的警方找不到任何線索，獸醫麗茲卻發現了關鍵跡象，使她懷疑兇手是一隻大獅子。一開始，她的理論不被重視，但在更多受害者出現後，人們開始相信這隻猛獅已經入侵阿姆斯特丹了。政府請來英籍的大型動物獵人與麗茲合作。然而，在調查的同時，她還得確保自己身為記者的男友不會為了新聞失了分寸。而另一邊，大開殺戒的獅子已即將讓整個城市變成牠的狩獵場。',
                'description_en' => 'A zoo veterinarian gets caught up in a grisly adventure as she finds herself leading the city-wide hunt for a monstrous lion terrorizing the Dutch capital of Amsterdam.',
                'year' => 2016,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/aRlCTDThpycG5VLpFef4SMnVrcA.jpg',
                'imdb_id' => 'tt5333264',
                'atmovies_id' => 'fpnl44291700',
                'douban_id' => NULL,
                'status' => 1,
                'created_at' => '2020-07-12 22:24:02',
                'updated_at' => '2020-07-12 22:47:53',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'title' => '長沙里之戰：被遺忘的英雄',
                'title_en' => 'The Battle of Jangsari',
                'description' => '韓國戰爭電影，梅根福克斯主演一名戰地記者，50年代仁川登陸戰後續。平均年齡17歲的學生兵們，該如何在惡劣的天氣中躲過槍林彈雨的攻擊，成功完成任務呢？',
            'description_en' => 'Korean War, September 1950. In order to fight the enemy forces based in the South of the peninsula, General MacArthur orders the start of the Incheon Landing Operation, deploying diversionary attacks in other locations. Without real military forces to spare, 772 very young Korean student soldiers, barely trained, are sent to Jangsari Beach, where they will face a heroic fate and discover the value of friendship… (A sequel to Operation Chromite, released in 2016.)',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/wHcV40sCtoI6wu10pJZ2Id6IUFF.jpg',
                'imdb_id' => 'tt9018916',
                'atmovies_id' => 'fbkr99018916',
                'douban_id' => '30309627',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:17',
                'updated_at' => '2020-07-12 22:48:17',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'title' => '蜈蚣降',
                'title_en' => 'The Queen of Black Magic',
                'description' => '哈尼夫帶著妻小和幾個好友，打算回到幼時成長的孤兒院，探望年事已高、身體孱弱的看護班迪先生。然而，當一行人抵達孤兒院後情況卻急轉直下，恐怖駭人的超自然事件接連襲來，本該溫馨的重逢場合一夜之間化為人間煉獄，揭露一段不為人知的黑暗過往……',
                'description_en' => 'Families were terrorized at the orphanage. Someone wants them dead, apparently with black magic that is very deadly. She has a grudge and she was also born because of the sins of the orphans who formed her into the queen of black magic.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/3Mzi1jWQmQKoNvAohLceELDNa5J.jpg',
                'imdb_id' => 'tt10656188',
                'atmovies_id' => 'fqin10656188',
                'douban_id' => '34825511',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:40',
                'updated_at' => '2020-07-12 22:48:30',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'title' => '大魔術師',
                'title_en' => '大魔術師',
                'description' => '《大魔術師》（英文：The Great Magician）是一部於2012年1月上映的的賀歲喜劇電影，根據中國作家張海帆於2009年發表的同名小說改編而成。由爾冬陞執導，梁朝偉、劉青雲及周迅聯袂主演。本片是劉青雲和梁朝偉繼1998年上映的電影《暗花》後相隔14年又一次合作的電影。',
                'description_en' => 'In the early 1920’s, on the streets of Beijing, the nation’s most talented performers have gathered to show off their most spectacular skills. One day, a challenge is set: 50 silver dollars to whoever can reproduce the incredible magic trick “Eight Immortals’ Treat”. Zhang Xian appears amidst the waiting crowd and decides to try his hand at it.',
                'year' => 2011,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/96k1xo0HLv0uzwefbUoAafaXBJg.jpg',
                'imdb_id' => 'tt1869721',
                'atmovies_id' => 'fghk49509007',
                'douban_id' => '4913200',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:49',
                'updated_at' => '2020-07-12 22:48:53',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'title' => '騎機男孩2',
                'title_en' => 'Bikeman 2',
                'description' => '阿薩考上銀行行員後，與佳茹戀情漸入佳境。佳茹便帶著阿薩和一群親友回老家拜訪父親。但佳茹父親是個老古板，希望為佳茹找到門當戶對的男友，因此伯伯裝起闊氣，浮誇的機車夥伴們化身落漆機師，一群人與古板父親撞出許多激情火花！',
                'description_en' => 'The story of Sakkarin continues from "Bikeman". Sakkarin is now on his full-speed hitting on Jai but love comes with as obstacle as he has to face with challenges posted by Jai\'s intimidating father.',
                'year' => 2019,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/wI9Qyvac4GZIiNS91JYOlNn61Ox.jpg',
                'imdb_id' => 'tt11204336',
                'atmovies_id' => 'fbth11204336',
                'douban_id' => '34960156',
                'status' => 1,
                'created_at' => '2020-07-12 22:24:58',
                'updated_at' => '2020-07-12 22:49:10',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'title' => '聲入奇境：經典配樂大師',
                'title_en' => 'In The Tracks Of - Special Edition',
                'description' => '繼《電影配樂傳奇》之後　最經典影史樂章
從法國新浪潮到當代好萊塢、從藝術經典到商業鉅作，看各個世代風格迥異的配樂家，如何成功化光影為音符。透過大師跨時空的分享，一窺經典電影背後，偉大樂章的靈感創生之路！',
                'description_en' => NULL,
                'year' => 2020,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/f5d5fcP5XxBzD1dVnK4C31MsHjt.jpg',
                'imdb_id' => NULL,
                'atmovies_id' => 'fien99602938',
                'douban_id' => NULL,
                'status' => 0,
                'created_at' => '2020-07-12 22:25:06',
                'updated_at' => '2020-07-12 22:42:11',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'title' => '戀愛完成式2',
                'title_en' => 'Present Still Perfect',
                'description' => '四年前，小拓和歐愛在他鄉的日本之戀無疾而終，令小拓深受打擊。苦等四年的小拓終於決定不再盼望歐回心轉意，並前往遠離泰國本土的孤島－閣骨島黯然療傷，也遇見來自日本的帥氣開朗男孩健太。島上的寧靜與美麗，終於令小拓重拾歡樂與笑聲。某天晚上，小拓突然收到歐的訊息、得知歐對他始終無法忘懷，卻也無法隱忍對歐仍然強烈的思念，即使他深知這段愛情不可能開花結果。隔天早上，歐竟來到閣骨島、出現在小拓的面前，他是否該聽從內心、與歐再續前緣？或是認清事實、與歐就此訣別？',
                'description_en' => 'Toey and Oat have to choose between “moral” and “desire”. Their love is meant to be beautiful, but it hurts people around them. How are they going to deal with it?',
                'year' => 2020,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/8A06KgbJ5sPVuNGjfbWds8oZiWP.jpg',
                'imdb_id' => 'tt10456640',
                'atmovies_id' => NULL,
                'douban_id' => '34926592',
                'status' => 1,
                'created_at' => '2020-07-12 22:25:15',
                'updated_at' => '2020-07-12 22:25:15',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'X+Y愛的方程式',
                'title_en' => 'A Brilliant Young Mind',
                'description' => '一名有自閉症邊緣性格傾向的小孩Nathan，他無法與人溝通，甚至排斥自己的母親Julie，唯有在數學的世界能使他找到慰藉。他進入了英國數學國家隊，跟著團隊遠赴重洋來到台灣參加國際數學奧林匹克競賽，直到在台灣遇上中國少女Zhang Mei讓他漸漸敞開了心房。',
                'description_en' => 'A socially awkward teenage math prodigy finds new confidence and new friendships when he lands a spot on the British squad at the International Mathematics Olympiad.',
                'year' => 2014,
                'poster_url' => 'https://image.tmdb.org/t/p/w185/jYkfSWb9rlTTzvLclCuJwm48kbl.jpg',
                'imdb_id' => 'tt3149038',
                'atmovies_id' => 'fxen33149038',
                'douban_id' => '25730893',
                'status' => 1,
                'created_at' => '2020-07-12 22:25:23',
                'updated_at' => '2020-07-12 22:40:40',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}